[book]
src = "src"
title = "Foundry Setup"

[output.html]
no-section-label = true
additional-js = ["solidity.min.js"]
additional-css = ["book.css"]
mathjax-support = true
git-repository-url = "https://github.com/owieth/foundry-setup"

[output.html.fold]
enable = true
